#!/usr/bin/env python3
# -*- coding:utf-8 -*-2
10
def bin2int(N):
    Sum = 0
    L = len(str(N))
    STR = str(N)
    a=0
    while a < L :
        if STR[a] == '0' or STR[a] == '1' or STR[a] == '.':
            a = a + 1
        else :
            a = -1            
            break     
    if a != -1:
        a = 0
        while L > 0:        
            n = int(STR[a])*(2**int(L-1))
            L = L - 1
            a = a + 1
            Sum = Sum + n  
        return Sum
    else:
        return -1 
    

if __name__ == '__main__':
    x = int(input("輸入一個二進位數:"))
    
    if x >= 0:
        ans = bin2int(x)     
        if ans >= 0:        
            print(x ," 的十進位表示為 ", ans)
        else:
            print("輸入錯誤")
           
    else  :
        ans = bin2int(-x)
        if ans >= 0:
            print(x ," 的十進位表示為 ", -ans)
        else:
            print("輸入錯誤")                