#!/usr/bin/env python3
# -*- coding:utf-8 -*-
10
def bin2int(N):
    Sum = 0
    L = len(str(N))
    STR = str(N)
    a=0
    while L > 0:        
        n = int(STR[a])*(2**int(L-1))
        L = L - 1
        a = a + 1
        Sum = Sum + n  
    return Sum

if __name__ == '__main__':
    x = int(input("輸入一個二進位數:"))
    
    if x >= 0:
        ans = bin2int(x)     
        print(x ," 的十進位表示為 ", ans)
        
           
    else  :
        ans = bin2int(-x)
        print(x ," 的十進位表示為 ", -ans)
                